### ISSUE TITLE
Add darkmode?

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#10]
I am usually not a fan of dark modes in apps, I never use them, but when dealing with flashcards I think dark mode really helps to protect your eyes. I like anymemo's darkmode as it is not full black but rather greysh (https://i.imgur.com/LsL51Xq.png)

I think it would be a nice addition.

ps: congrats for f-droid inclusion 👍

**Comment by tema6120** [comment]
Thank you 😊. Yes, dark mode is at the top of my todo-list.

**Comment by tema6120** [comment]
Dark mode is implemented in v1.7
