### ISSUE TITLE
When editing a card the space is smaller than reality

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#12]
When you edit the card the text only reaches a certain point on the right of the card then it forms another line below. However when you leave editing mode the card has a white space (about 1/4 of the whole width) which could have been used instead of forming another line. ForgetMeNot should use all the space available so one can write more and avoid making long cards. I hope I was clear enough to explain the issue.

**Comment by tema6120** [comment]
I understand what you mean. The reason why you might think so is that there is padding 16dp on the sides.
![screenshot with padding](https://user-images.githubusercontent.com/34657415/96555489-8471bf80-12c0-11eb-9f78-335bf37f4461.png)
Taking into account padding, it's normal that TextView wrap text onto another line.
