### ISSUE TITLE
Allow selection of multiple flashcards when in edit mode

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#13]
Right now to delete a card I need to click on it and press the bin icon. I think it would make more sense to keep pressed and have a pop-up for deleting/moving the card, like many apps have. I feel having to click on the card and the press the button is redundant, especially if you want to delete several cards. Pressing to select and delete with a button would make easier mass deletion. WHat do you think of this feature?

**Comment by tema6120** [comment]
Accepted. Thank you for continuing to give me feedback. I appreciate it 🤗

**Comment by WPFilmmaker** [comment]
@tema6120 thanks to you for being so responsive! 🤗 The app is quite complex so only by using it one can provide feedbacks to improvement, and since I decided to use ForgetMeNot as main app for repetition it is easy :D

**Comment by tema6120** [comment]
I have implemented card selection in v1.5
![Webp net-resizeimage (9)](https://user-images.githubusercontent.com/34657415/110360319-4135a480-8047-11eb-8355-78e631d4eb6d.png) ![Webp net-resizeimage (10)](https://user-images.githubusercontent.com/34657415/110360344-47c41c00-8047-11eb-8ca6-1dcab7553a6a.png)
