### ISSUE TITLE
When you finish a repetition you should be back to main menu

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#15]
Right now when you finish a repetition the user does not know what to do and has to use the android arrow to go back to the menu. It would make more sense either to ask to start repetition again or to return to the main menu.

**Comment by tema6120** [comment]
I plan to add last page with statistics. So, this screen will have additional action

**Comment by tema6120** [comment]
I did as you proposed:
![Webp net-resizeimage (7)](https://user-images.githubusercontent.com/34657415/105889214-9af18a80-6016-11eb-8b33-98ea1324b0c5.png)
