### ISSUE TITLE
Automatically center words

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#16]
I don't know if it is tricky to implement but when there is one word (or maybe word + article) it is nice to see the top card text centered, however this does not happen with the lower one which is put on the left and one has to manually adjust it. I think it would be great if ForgetMeNot would automatically center the text of lower card too (unless specified)

**Comment by tema6120** [comment]
I already mentioned in [this comment](https://github.com/tema6120/ForgetMeNot/issues/11#issuecomment-711168672), that I'm going to give the user a choice of text alignment for the question and answer separately in general settings.

**Comment by tema6120** [comment]
it became possible since version 1.6 in Settings -> Card appearance
