### ISSUE TITLE
Ability to invert card during repetition

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#17]
Right now when you repeat the order of cards is top-down, but I think it would be nice to have an option to select before you start to switch to down-top, I find repetition with spoken text quite useful while walking, I heard the word in my target language, i pronounce the translation in english and then listen to the english translation of the card to be sure I am right. So it would be nice having the opposite to add variety.

**Comment by tema6120** [comment]
if I understood correctly, it's already realized. Check 'Card reverse' in deck settings.

**Comment by WPFilmmaker** [comment]
I checked and you are right, but this is kinda related to  #19 as this option is buried in the settings of each deck, I would make it more visible (for example add a setting in the repetition first page), so that user can change it on the fly.

**Comment by tema6120** [comment]
Ok. I will provide the ability to edit deck settings in  the exercise like I dealt with card content editing.

**Comment by tema6120** [comment]
As I promised:
![ScreenRecord-2021-02-01-17-47-41 (1)](https://user-images.githubusercontent.com/34657415/106483179-eabccf80-64b6-11eb-8205-e73a44242c9e.gif)
