### ISSUE TITLE
[question] how to do quiz more than once?

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#18]
I haven't been able to figure out how to do quiz more than once, i think the limit is once a day right? I think user should have freedom to repeat the quiz as many times per day as they prefer.

**Comment by tema6120** [comment]
The learning process is based on [Spaced repetition](https://en.wikipedia.org/wiki/Spaced_repetition) for effectiveness of memorization. Once you answered, it will take some time for the card to be available back for the exercise. The waiting time is defined by level of knowledge.
![Level of knowledge](https://user-images.githubusercontent.com/34657415/96959227-30f1b280-1508-11eb-8caa-dfde26a48a21.png)
The better you know the card, the less often it is asked.

For each deck you can change intervals scheme as you like:
![Intervals](https://user-images.githubusercontent.com/34657415/96959509-ec1a4b80-1508-11eb-8c34-e9d5e652187a.png)

If you don't like the idea of Spaced repetition you can turn it off:
![Intervals are off](https://user-images.githubusercontent.com/34657415/96959628-2552bb80-1509-11eb-959f-936ab900f085.png)
