### ISSUE TITLE
make ForgetMeNot more 'finger friendly'

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#19]
This is a feedback result of using ForgetMeNot, while I sit at table I have no issue clicking on the 3 dots to open menu and start a repetition, however while walking/standing up, I feel using the finger to tap on a deck is more natural than clicking on dots. I propose to add that when you tap on decks a popup asks the user to start a repetition or a quiz, so that one can access to them quicker, and use the dots only when you are in a more comfortable position

**Comment by tema6120** [comment]
I will consider it.

**Comment by tema6120** [comment]
First of all I renamed 'Repetition mode' -> 'Autoplay'.

So we have two main mode: 'Autoplay' and 'Exercise'. I made two buttons for them at the bottom of deck list screen:
![Webp net-resizeimage (6)](https://user-images.githubusercontent.com/34657415/105888316-7d6ff100-6015-11eb-97a1-d3b9413873e9.png)
