### ISSUE TITLE
Reorganize "help" menu

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#2]
Right now help menu is very informative but it is buried under the menu,
You have to click on 3 dots, help and then again 3 lines to have the list of topics. Also the about ForgetMeNot is there (which to me makes little sense)

I propose:
Move "about" in the 3 dots menu 
(sort by
filter
Settings
Menu
Help)

Make the list of help available once you press "help" instead of having to press the 4 lines

**Comment by tema6120** [comment]
![ScreenRecord-2021-01-26-21-22-14](https://user-images.githubusercontent.com/34657415/105895632-6b468080-601e-11eb-9894-2429f06b0bdf.gif)
As you can see I moved some items to the side menu. I heed your advice and showed the list of help articles at once
