### ISSUE TITLE
add more meaning to the flower icon in the top bar

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#20]
I like the idea of the flower icon in the top bar telling me which word i am using, however i feel more meanig can be added by showing the percentage of cards left, something like "ciao" (2/10) to symbolize that "ciao" is the second card of a 10 cards deck.

**Comment by tema6120** [comment]
Accepted. I will also add progress bar in exercise.

**Comment by tema6120** [comment]
In 1.5 card position is displayed both in the notifications and in the application itself
