### ISSUE TITLE
allow a proper quiz mode

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#21]
Right now if I am on a card I can select quiz, however once i answered through the chosen quiz, nothing happens and I have to use my finger to swipe to the next card which is not asked in quiz mode.

I understand that such quiz can be used just to help to remember one word but I think it would be nice to have a proper 'quiz' mode where user can challenge themselves with all flashcards presented as quiz (multiple choices, hidden letters and so on). 

This would add challenges and in the future it could be extended with other types of quizes.

This would make ForgetMeNot not just a flashcards app but a more complete learning experience, as different quiz modes can be more challenging, without the need to install another app-

**Comment by tema6120** [comment]
You can choose 'Quiz' as test method for specific deck. Check it out in deck settings:
![Test methods](https://user-images.githubusercontent.com/34657415/96960859-1b7e8780-150c-11eb-9935-aec4a223dc01.png)

**Comment by WPFilmmaker** [comment]
@tema6120 thanks a lot! I feel this is related to #19 as this option is buried in the settings, and user can't change it on the fly, so please when you deal with  #19 keep this ticket in mind too :)
