### ISSUE TITLE
multiple exports

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#22]
Right now it is not possible to export multiple decks at the same time, which is annoying if you have several, it would be great to being able to select all and then 'export all' :)

**Comment by tema6120** [comment]
Accepted.

**Comment by tema6120** [comment]
Multiple export is implemented in v1.5. It also became available to export decks in other formats:
![Webp net-resizeimage (11)](https://user-images.githubusercontent.com/34657415/110361445-b05fc880-8048-11eb-8a02-2ab6e6591b52.png)
