### ISSUE TITLE
ability for cards to resize

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#23]
Right now the top and bottom part are the same size, however it happens that I want to remember verb so I put the infinitive verb in my target language and in the bottom one the meaning and all the conjugations. I don't know if this is a standard use of ForgetMeNot, but I have to say it worked well. One aspect which I think could be improved is the ability to have different sizes. Let me explain.

When I see the verb it is nice to see that both cards are the same size, however once I click remember/not remember and the lower card has all the conjugations, I have to scroll in order to see all the content, which could be avoided if the upper card would resize to say 1/3 so that the lower one could increase making 2/3 of the both cards. Since top card has just a word it is not necessarily for it to be the same size as the lower where several words are included.

I hope you don't feel overwhelmed by my feedbacks but the more I use the app the more I like it and consequently the more feedbacks you get :D

**Comment by tema6120** [comment]
Yes. I thought about this earlier. And what I came to was to allocate space proportionally to the contents of the cards. It would reduce the probable scrolling. It just some tricky to realize. So I put it off until late.

I will gladly accept you feedback. That's good, keep it up)

**Comment by tema6120** [comment]
Realized. Now the card tries to fit everything avoiding scrolling.

![card space allocation](https://user-images.githubusercontent.com/34657415/105886978-c3c45080-6013-11eb-8d42-a2d5581ae913.png)
