### ISSUE TITLE
ForgetMeNot should pause repetition if a call is received

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#24]
Yesterday I was doing repetition with audio reading text and I got a call on skype, I picked up but ForgetMeNot kept going on with the flashcards so I had to minize the call and pause the repetition, missing a few cards. I don't know if the same happens with other software but I think when a call is picked up ForgetMeNot should pause repetition so that once I am done with the call I can continue.

**Comment by tema6120** [comment]
Implemented.
