### ISSUE TITLE
Allow user to draw on cards

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#25]
First of all thank you again for ForgetMeNot! I have been using for a week or so and it has been great. I thought about a feature which imho could be useful in two ways.

I would like to request the ability to draw freely on cards (maybe with a thickness selector and a few colors). This would serve two purposes. Highlight parts of the flashcard without having to use rich text, allow user to add an image to the flashcard while keeping it easy and lightweight.

For some languages there are letters you don't pronounce so I imagined it would be nice if a user wanted to draw a line under that letter to highlight it, as well as to make a quick sketch of a washing machine if they are trying to remember the word for washing machine (both cases are how I would use such feature).

For me especially drawing a quick sketch would be very useful as it is similar to have images but it is simpler and keeps the app more lightweight (and it is also fun if you draw your own stuff).  

Nowadays almost every photo editor has such drawing feature, even chrome has it, and I think it can be very useful. If a user uses a pen they could even write quick notes on the flashcards.

**Comment by tema6120** [comment]
I'm sorry but I'm not going to implement this feature. The main reason for this is that, although it sounds great, it's difficult to implement. In the short term I'll focus on supporting plain text only. Maybe in the future I will provide support for other formats.
