### ISSUE TITLE
Ability to add random card inversion during repetition

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#27]
I realized that, at the least for me, using targetlanguage-mylanguage flashcards is easier than the other way around, and I go for the latter option only when I am comfortable to remember them. 

Today I accidentally repeated two decks one with inverted cards and one without. It was a fun experience that led me to open this ticket.

I think it would be great having an option to select a random card inversion during repetition (so some cards are inverted some not), I think it is challenging as you don't know what to expect in the next card, and it adds a bit of complexity which is good when you are learning a language.

Ideally you would have this implemented as #17, so before you start repetition you can decide which mode, normal, inverted or random.

**Comment by tema6120** [comment]
A good idea! I will definitely implement it. Thanks again for continuing to come up with new ideas!

**Comment by WPFilmmaker** [comment]
@tema6120 Thanks to you for keep working on this! I am glad you appreciate my feedbacks. I don't have much experience with flashcards app (and I was skeptical whether they actually worked or not), but I have been using ForgetMeNot every day for a few weeks and I can see the results!

**Comment by tema6120** [comment]
As of v1.3 you can enjoy this feature.

**Comment by WPFilmmaker** [comment]
@tema6120 You are doing a great job!
