### ISSUE TITLE
Feature Request: mask letters hint mode: reveal one word at a time

### ISSUE THREAD

**Issue by zachdecook** [tema6120/ForgetMeNot#29]
I use this app to memorize scripture passages, sometimes containing over 100 words in the 'answer' field.

The 'mask letters' mode is helpful, because it can remind me of the length of the words, but if I'm halfway through a passage, and need a hint, it's really annoying to have to push the 'hint' button for each letter (a few hundred times) until I've caught up to where I am.

It would be great if the hint button revealed one word (or more) at a time instead.

Perhaps the amount revealed could be automatically determined based on the length of the answer. (Surely, nobody wants to have to click the hint button over twenty times per card). 

Thanks for the great software!

**Comment by tema6120** [comment]
I am glad that you find my app useful :) I think this feature has already been implemented. You should highlight the text you want to reveal and click hint icon again. This is how it works:

![hints](https://user-images.githubusercontent.com/34657415/103369914-0b6ac180-4ad4-11eb-86e1-b0433056d53a.gif)

Is that what you wanted?

**Comment by zachdecook** [comment]
Oh cool! That's certainly much easier than pressing the button repeatedly!
