### ISSUE TITLE
Improvements to the "about" page

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#3]
Right now the about page is quite scarce of details. Usually about pages have logos,devs,license, contacts etc.

Right now none of this is present so the about is quite useless as it does not provide the main info (for example version to report a bug here)

I propose to add:
ForgetmeNot logo
name of dev
version of software
License

**Comment by tema6120** [comment]
Agree! 'About' page is crappy and not in the right place. It will be fixed.

**Comment by tema6120** [comment]
Done!
![Webp net-resizeimage (8)](https://user-images.githubusercontent.com/34657415/105889663-1bb08680-6017-11eb-83fa-5f76a1cb412c.png)
