### ISSUE TITLE
Automatic darkmode when low battery

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#30]
I wasn't sure whether to open this ticket or comment on #10 as it is related to it.

On Android 10 (and maybe earlier?) apps can go in dark mode automatically when battery reaches low levels, telegram and whatsapp do this for example. I think it would be very useful if forgetmenot would do that too. Ideally once battery is full again darkmode would disable itself (unless chosen by the user in settings).

**Comment by tema6120** [comment]
Agree! When I get my hands on dark mode I will do something like this:
![output-onlinepngtools (2)](https://user-images.githubusercontent.com/34657415/103425872-f66a5d00-4bbd-11eb-9bb1-80aeaecba2b0.png)

**Comment by tema6120** [comment]
As I promised:
<img src="https://user-images.githubusercontent.com/34657415/112977780-21356480-915f-11eb-9e43-341e9658536f.png" height="640">

**Comment by WPFilmmaker** [comment]
@tema6120 Thanks a lot!
