### ISSUE TITLE
A few suggestions to improve home screen

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#32]
I just updated and found the new version cool, of course quite different from the previous one, I see that you put a lot of efforts in this app and I want to say thank you, I use your app daily.

I have a few suggestions which I think could improve the interface:

1 Remove the black dots next to the name of decks (it does do anything and it adds black to the interface)

2 Use one font (max 2) for the interface (in my case https://imgur.com/a/vj7YKos considering cyrillic alphabet, latin with upper and lower cases, I have 5 fonts in one screen which are not nice to read IMHO)

3 In my opinion the new font used for decks is less clear than the previous one, it looks more modern/cartoonish but less readable IMHO, what do you think? I feel font should be as neutral as possible for better readability or user ought to have a choice to change it)

4 Dark grey Copyboard symbol (right now it is orange, I don't know if it is orange all time or only when you have something to paste, imho it adds unnecessary distractions, I think user don't paste things in the search bar all the time so I feel it is not necessary for that symbol to be orange).

I hope you will appreciate my feedbacks, they want to be ways to improve not criticism ;)

ps: in the developer story (which I enjoyed reading!) there is a missing word, 'because a deck can **be** created on a computer'

**Comment by tema6120** [comment]
1) About bullet:
    Perhaps I was in a hurry to display it, but in the future it will have its own purpose. It can be colored and will symbolize the group to which the deck belongs.

2) About fonts
    This is of course a matter of taste, but I agree that the number of fonts used is large. Well, I changed the font for some titles to a more general one. This is how it has now become:
![Screenshot_20210128-012517](https://user-images.githubusercontent.com/34657415/106067646-c902c780-6107-11eb-95f7-69567fc4c9a3.png)

3) About 'paste' button
    Personally I often use copy/paste operations. And having this button, it significantly speeds up working with inputs. As for the color, this button is always orange and I like how it looks like ;)
