### ISSUE TITLE
Bug: rotating screen during autoplay causes 3 issues

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#33]
With 1.2 on my Moto G7 Power (from GooglePlay), when I do a repetition of a deck with 'autoplay' and I rotate the screen horizontally three things happen:

- Autoplay stops and I need to manually press play again
- Repetition starts again from beginning
- Lower cards are not grey and covered any more, they are white and the content is clearly visible.

How it is reproducible on my system:
1 Start autoplay with a deck (phone vertical)
2 Rotate phone horizontally
3 Rotate again vertically
4 Press play and rotate vertically

This did not happen with the previous version so they must be bugs introduced with this version. It is annoying because sometimes one like moving the phone, so I hope you can fix these issues. Is there any other way I can help you with more info?

edit: using split screen with ForgetMeNot and another up below cause repetition to start again as well.

**Comment by tema6120** [comment]
This is my omission. I have already fixed this.
