### ISSUE TITLE
Add back number of repetition in autoplay (1.2)

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#34]
I like that you added infinite repetition which can be easily toggled on/off while doing autoplay, however you removed the way to add numbers of laps for each repetition when you press autoplay, which I think is a step backwards as now If user want to do another cycle of repetition (or more) they have to wait til the end and press play again. Can you please add it back?

**Comment by tema6120** [comment]
I doubted a little if I was doing the right thing to remove this feature. Thank you for confirming my doubts). I will try to bring this feature back to the next release.

**Comment by tema6120** [comment]
Fixed. And now it is possible to change number of laps dynamically in card player.
