### ISSUE TITLE
Будет ли возможность работы программы с ксв файлами?

### ISSUE THREAD

**Issue by vast4343** [tema6120/ForgetMeNot#35]
Добрый вечер Артем. Обновленный интерфейс очень понравился. С переводом программы на русский открыл некоторые новые функции. Единственная печалька копирование по одной фразе много времени занимает, особенно когда диалог не на 5 строк. Жаль у вас нет Ексель. Я пробовал сохранить тексты из файла ексель в файл txt: и с кодировкой utf-8 и без нее, почему-то пишет неправильный формат. Или кирилицу не отображает. Вы вроде хотели сделать в программе возможность работы с ксв файлами. Жду не дождусь этого. Только можно сделать, чтобы кирилицу без кавычек программа читала, иначе каждое слово/фразу еще и в кавычки нужно будет брать, а это еще дольше получится. Спасибо за программу еще раз, она у вас замечательная.

**Comment by tema6120** [comment]
Спасибо за ваш отзыв. Я постараюсь сделать поддержку .csv файлов к следующему релизу. Это действительно один из главных недостатков моей программы.

По поводу текущего формата:
```
Q:
river
A:
река


Q:
mountain
A:
гора
```
Этот формат я придумал специально для своей программы для того, чтобы удобно было вручную создавать текстовые файлы. Конечно же txt файл, которые экспортирует Ексель, не будет соответствовать моему формату.

CSV - это общепринятый формат, и отлично подойдет, если ексель таблица будет содержать строго два столбца. Единственное, что меня сдерживает это некоторые неоднозначности этого формата. Вот [здесь](https://ru.wikipedia.org/wiki/CSV) более подробно. Идеально было бы предоставить некоторый UI для уточнения формата CSV (например разделитель) в случае если CSV-файл пользователя немного с "особенностями".

Так что все будет) Постараюсь решить вопрос поскорее.

**Comment by vast4343** [comment]
Для меня наиболее удобен разделитель Tab, т.к ексель позволяет сохранять в текстовый файл с разделителем Табуляцией. В других программах работающих с CSV приходиться делать след. операции. Сохранять сначала в txt с разделитель Tab. Затем открыв в текстовом редакторе сохранить в кодировке utf-8, затем вручную исправить расширение на CSV. После этого данные программы позволяют импортировать файл в себя.
п.с. Еще ексель позволяет сохранять в txt (Юникод) - не применял , т.к. проги это не видели.
п.с. Так же ексель позволяет сразу сохранять в CSV (с разделителем запятая) - тоже не применял. 
п.с.с. Главное много программ для повторения слов, для отображение кирилицы требуют заключать фразы на русском в кавычки, этого хотелось бы избежать.

**Comment by vast4343** [comment]
Может вообще лучше оставить работу программы с txt файлами, но чтобы при конвертации из ексель, ваша программа позволяла их импортировать.

**Comment by vast4343** [comment]
С кодировкой разобрался - как и у другого пользователя тоже была: utf-8 с BOM. Теперь все работает. Пока полуавтоматизировал процесс: 100 фраз из 2-х столбцов ексель могу перевести в нужный формат за время около 2 - 3 мин.

**Comment by tema6120** [comment]
Я выпустил версию 1.4 в которой реализовано поддержка любого формата с разделителями (CSV, TSV). Единственно что нужно, это указать уточнения формата. Можно выбрать среди предопределенных или создать свою. [Здесь скриншоты](https://github.com/tema6120/ForgetMeNot/issues/1#issuecomment-783409777). Также есть встроенный редактор исходного текста с подсветкой вопросов и ответов.

Напишите пожалуйста, удалось ли вам импортировать файл без скобок или возможно что-то не так работает.

**Comment by vast4343** [comment]
Добрый вечер Артем. Как я и написал в отзыве на гугл плей: сначала прочитав справку я думал, что нужно все фразы брать в кавычки. На самом деле не нужно, просто при импорте колоды, необходимо выбрать нужный формат, из предлагаемых программой. Сделал несколько файлов ксв: сохранял из ексель сразу как ксв (разделитель автоматически ставиться точка с запятой), далее сохранял из ескель как .txt с разделителем Tab и потом как ксв - затем оба сохранил с кодировкой текста utf-8 без BOM. В третьем файле csv оставил кодировку Кирилица, и при импорте выбрал ее, и программа импортировала файл без ошибок. Единственное когда попытался импортировать файл на 450 фраз программа написала: "Слишком большой файл для редактирования" и затем при сохранении колоды: файл содержит 2550 ошибок. Потом еще раз посмотрел файл, а у меня после 450 строк далее шли Табы на каждой следующей пустой строке, всего в файле было 3000 строк. Когда убрал все ненужные Табы, все импортировалось в программу. Единственное чего не хватает: возможности переноса из одной папки в другую, счетчика слов при тестировании (сколько осталось до конца в папке), и ночного режима. Спасибо за программу, очень нравиться!

**Comment by tema6120** [comment]
"Слишком большой файл для редактирования" - это намеренный ход, потому что если большой файл, все начинает дико зависать. Такой режим включается, когда символов в файле больше 20_000.

На счет пустых строк. Можно создать свой DSV формат и включить "Игнорировать пустые строки". Кстати, при создании своего формата (при нажатии кнопку '+'), новый формат будет копией того, что было выбрано до этого.

Спасибо большое за отзыв на Google Play и 4pda). Было интересно читать)

На счет ваших предложений. Перемещение карточек и счетчик будет реализовано в ближайшем будущем, а с ночным режимом нужно немного подождать
