### ISSUE TITLE
ForgetMeNot does not recognize RHVoice (TTS)

### ISSUE THREAD

**Issue by KosmoEskudo** [tema6120/ForgetMeNot#36]
RHVoice is a TTS engine. I have installed RHVoice from F-Droid (v. 1.2.3), and downloaded the Esperanto language. I have set RHVoice as preferred engine, and selected Esperanto from Android's *Text-to-speech output* settings. I installed ForgetMeNot from F-Droid (v. 1.2). When creating a deck, then create a card, general> pronunciation> question> Esperanto (which appears with a flag and a question mark). Then, when testing it, it pops up "Current TTS engine (com.github.olga_yakovleva.rhvoice.android) doesn't support Esperanto."

What can I do?

**Comment by tema6120** [comment]
It seems a bug of RHVoice. I've noticed that this only happens with Esperanto. I created [an issue](https://github.com/RHVoice/RHVoice/issues/263) on RHVoice page.
