### ISSUE TITLE
Wrong card format when importing a deck

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#37]
I made a long deck in the format:

﻿Q:
Mилан
A:
Milan

Q:
Венеция
A:
Venice

And saved as .txt. However when I try to upload I get:

wrong card format: Q:
Mилан
A:
Milan

I checked the deck again but everything seems fine, what am I doing wrong? :(
ForgetMeNot v1.2

**Comment by tema6120** [comment]
Please share txt file

**Comment by WPFilmmaker** [comment]
@tema6120 https://filebin.net/36ofcxom7jwwkqw8 can you download it?

**Comment by tema6120** [comment]
Yes. Now see

**Comment by tema6120** [comment]
Fixed. Thank you) The problem was that my app didn't take into account the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) character.

**Comment by WPFilmmaker** [comment]
thanks to you for the quick fix! So it means that my deck was fine right and that I have just to wait for a new release to see it working?

**Comment by tema6120** [comment]
Yes. If you want to import file in this version you need to remove BOM character. For example, in Sublime you need to save with encoding UTF-8, but not UTF-8 with BOM:
<img width="807" alt="Screenshot 2021-01-30 at 02 06 20" src="https://user-images.githubusercontent.com/34657415/106339739-2af63500-62a0-11eb-8c64-29221fffb2b5.png">

As bonus I fixed your file:
[________cities_.txt](https://github.com/tema6120/ForgetMeNot/files/5896981/________cities_.txt)

**Comment by WPFilmmaker** [comment]
Thanks!
