### ISSUE TITLE
Тёмная тема сломана

### ISSUE THREAD

**Issue by ACactUs** [tema6120/ForgetMeNot#39]
Версия: из FDroid v1.2
При включенной тёмной теме на устройстве в приложении она работает лишь частично. При этом в меню колоды и при редактировании карточек - чёрные буквы на тёмно-сером фоне.
Предлагаю также добавить переключатель, чтобы можно было выключить тёмную тему в приложении.

![Screenshot_20210131-162328](https://user-images.githubusercontent.com/25302233/106379826-30a76400-63e1-11eb-840d-a9c752e90172.png)
![Screenshot_20210131-162414](https://user-images.githubusercontent.com/25302233/106379830-3309be00-63e1-11eb-9cd3-23eb9d1f82c0.png)
![Screenshot_20210131-162439](https://user-images.githubusercontent.com/25302233/106379834-369d4500-63e1-11eb-9bc7-84e84be48da5.png)
![Screenshot_20210131-162454](https://user-images.githubusercontent.com/25302233/106379839-3b61f900-63e1-11eb-9086-05c4a7f68fcf.png)
![Screenshot_20210131-162500](https://user-images.githubusercontent.com/25302233/106379840-3e5ce980-63e1-11eb-8daf-4574c69413bd.png)

**Comment by tema6120** [comment]
Мое приложение пока не поддерживает темную тему, а то, что сейчас можно видеть - это ОС Android пытается принудительно перевести. Темная тема будет реализована, но немного попозже.

**Comment by tema6120** [comment]
В версия 1.7 темная тема полностью реализована:
<img src="https://user-images.githubusercontent.com/34657415/112978328-dcf69400-915f-11eb-97f3-01c849e5254e.png" height="640"> <img src="https://user-images.githubusercontent.com/34657415/112978343-e4b63880-915f-11eb-836f-b3b1ca9976ae.png" height="640">
