### ISSUE TITLE
Subdecks

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#4]
Right now if I want to have a deck for verbs, one for adjective etc. I need to create several decks e.g. "italian verbs", "italian advjectives", which I think can work if you are using ForgetMeNot just for one language/topic, but once you start using it for several I think it can become tricky as the list grows.

It would be nice to have a sort of subdeck, so I click on 'deck italian' and if subdecks are presents a list shows under it and i can open the right deck. Of course there should be an option to repeat a single subdeck or the whole deck.

I don't think this feature is present but I think it would be very useful.

**Comment by tema6120** [comment]
To date, there is no grouping of decks. I myself suffer from the lack of this feature ;)

I'm thinking about the design of this feature and I'm leaning towards the idea of labels. One or more labels can be attached to each deck. The labels can be used in the deck filter. Also, labels can be used to display statistics for the desired group of decks.

**Comment by WPFilmmaker** [comment]
Yes I was thinking about possible approaches and labels sounds like a good idea!

**Comment by tema6120** [comment]
Grouping decks is implemented in v1.6. I introduced the groups as 'Deck lists'. Deck list should be named and have color. Deck lists can have the same decks. For example, deck "Idioms 23" can be included in deck lists "English", "English idioms", "Bad studied" at the same time.
[<img src="https://user-images.githubusercontent.com/34657415/112142757-aa88ec00-8bdf-11eb-8164-48529c7d9155.png"  height="640">] [<img src="https://user-images.githubusercontent.com/34657415/112142750-a8bf2880-8bdf-11eb-97b6-e0d7126201a6.png"  height="640">]
