### ISSUE TITLE
Improvement to repetition without time interval

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#41]
For decks I am learning I use time intervals, however once I am familiar with them I remove the limit so I can exercise less often but when I do i can do it several times.

Right now when I select multiple decks, repeat them, I reach the final card but no other option is given. I have to go back to the main menu but the previously selected decks are deselected so if to repeat them I need to reselect them again.

I think it would be nicer if at the end of repetition user would be offered to repeat the repetition again or go back to the main menu, as it happens for decks with time intervals.

**Comment by tema6120** [comment]
What do you mean by 'remove the limit'?
What testing method do you use?

**Comment by WPFilmmaker** [comment]
Sorry for not being clear enough, I am using self-testing  and intervals: off.

**Comment by tema6120** [comment]
I considered your proposal and decided to reject it. This breaks the learning plan. After all, it is assumed that if the card is answered correctly, it should not be asked in the same session. There's nothing wrong with repetition again but the usual way of learning process in my app does not imply to repeat for round two if they are already answered as right.
