### ISSUE TITLE
Bug while renaming deck (and changing app)

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#42]
Let's say you have a deck called xxxx and you want to rename it to yyyy

How to reproduce::
1 rename xxxx to yy
2 you don't remember the whole name so you want to check another app for the correct spelling of yyyy
3 open another app
4 go back to forgetmenot to complete yyyy but instead of yy you will see xxxx

It is a bit annoying when you try to check the correct spelling of a word.

**Comment by tema6120** [comment]
Fixed! Also this bug was manifested in some other dialogs.
