### ISSUE TITLE
Add back customized intervals

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#43]
Before 1.2 you could add personalized intervals to decks, either default, personalized for a specific deck, or a personalized interval for another deck which you could use for other decks as well.

As 1.3 I can't find this option anymore and IMHO it is a regression compared to before, as it was very useful to change intervals quickly when you have many decks, could you add it back?

**Comment by tema6120** [comment]
Yes. I removed the feature of presets nested in another presets such as presets for Pronunciation, Intervals and Pronunciation plan. In my analysis it can lead to bad user experience. When nested preset is edited, it modifies not only outer preset from which it was called but other outer presets that refer to this nested preset. In simple words it can lead to unexpected changes.

As alternative just create another preset of deck settings with another intervals.
