### ISSUE TITLE
Can't export

### ISSUE THREAD

**Issue by maemunman** [tema6120/ForgetMeNot#44]
When I press export, it says, "You don't have any file manager to create  a file".  I, in fact, have not one but _four_ file managers installed.  The stock Samsung one, "Material Files" from Fdroid, "Simple File Manager" from Fdroid, and "Ghost Commander" from Fdroid.

Which open-source file manager does the app support?  I'm on v1.2 since fdroid's repo doesn't have 1.3 yet.  I'll update this ticket if anything changes with 1.3

**Comment by tema6120** [comment]
At this point my app relies on a file manager that supports the ability to create a file for another application as described [here](https://developer.android.com/guide/topics/providers/create-document-provider#creating). Although many file managers provide the ability to read a file, unfortunately, very few support the ability to create a file (I know only two app: stock file manager and Google Drive). It's a problem.

What are my plans to fix this:
To get rid of the dependency on other applications, I plan to embed my own file explorer. The next release (v1.4) will be entirely dedicated to import/export of cards. It will bring such features as multiple import/export of decks, .csv support, support for encodings (other than UTF-8) and others.

**Comment by barudaret** [comment]
Oh ok, no worries.  I mean, I'm sorry to say, but I _do_ also have Google Drive installed.  In theory, Drive should be able to make it work, yeah?  It doesn't for some reason.

**Comment by barudaret** [comment]
God bless you, man, I see the work you're doing on this.  I appreciate you

**Comment by tema6120** [comment]
In version 1.5, I slightly changed the code regarding export. Maybe it will work this time but I'm not sure.

As for own file explorer, I changed my mind about implementing this for some reasons. But this is not the end of the story. I have some plans for an alternative solution.

**Comment by maemunman** [comment]
It has been working for me. I think we can close this. Reopen if you disagree ofc. @tema
