### ISSUE TITLE
Расстановка колод вручную, при сортировке колод

### ISSUE THREAD

**Issue by vast4343** [tema6120/ForgetMeNot#50]
Добрый вечер Артем. Можно попросить в сортировку колод добавить возможность расстановки колод вручную, чтобы расставить и закрепить их как мне нужно и не ждать пока новые колоды не уйдут вниз. У меня 3 базовые колоды по 100 слов и 3 рабочие колоды куда перекидываю по 20 слов из базовых, и там учу. Мне было бы удобно сразу поставить их в нужном порядке (независимо от названия, задания или частоты использования) и закрепить, чтобы они не менялись местами.

**Comment by tema6120** [comment]
Почему бы не воспользоваться списками колод?
![ScreenRecord-2021-04-02-02-04-25](https://user-images.githubusercontent.com/34657415/113363323-3c6bc400-9359-11eb-9e88-4c3de894024e.gif)

Еще интересно, почему вы именно делаете отдельные колоды для учебы. Подозреваю, вы хотите ограничить количество карточек для упражнения. Если это так, то хочу сообщить, что в следующей версии появится возможность  указывать максимальное количество карточек для упражнения. Код уже написан.
<img src="https://user-images.githubusercontent.com/34657415/113363751-5e197b00-935a-11eb-869b-0785b9807c4d.png" height="640"/>

**Comment by vast4343** [comment]
Фильтры пробовал, спасибо. Просто, подумал, будет удобнее сортировать, когда будет много тематических колод: в аэропорту, в гостинице, в кафе, в городе и т.д. В принципе, можно сразу все колоды последовательно пронумеровать и сортировать по названию, а те, что учишь сейчас, действительно отфильтровать. Спасибо за цветные маркеры фильтров - не знал.
Количество карточек ограничиваю небольшим числом, т.к. работаю с ними несколько дней подряд, доводя до высокой скорости повторения, перед тем, как задавать им режим интервального повторения.
