### ISSUE TITLE
Option to decide how many laps for autoplay

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#51]
I updated to version 1.7 and I can't find the option to decide how many laps to do for autoplay, was it remove?

Something which might be connected (I can't test it since I cant find the way to change laps): 

With this version if you don't do all lapses, the day when deck was used does not change, I think it shouldn't be the case (basically you select 2 lapses, do only one but ForgetMeNot does not recognize that lap).

I (think) was doing 2 laps, after 1 I stopped (I noticed that the deck started again from beginning after ending so I think I had two or more laps) and checking last time I used the deck the app still showed the old time.

**Comment by tema6120** [comment]
Just swipe on control panel and you will find 'Laps' button.
![ScreenRecord-2021-04-03-14-22-14](https://user-images.githubusercontent.com/34657415/113477274-5efcfa80-9489-11eb-91c1-e5219e4ac41f.gif)

**Comment by WPFilmmaker** [comment]
@tema6120 Thanks a lot!
I checked and I did 1/2 laps, so the issue is confirmed, ForgetMeNot does not recognize as done when you don't do all the laps you set (which I think should), what do you think?

**Comment by tema6120** [comment]
I cannot get what you mean. Can you put it in another words? Maybe screenshots would clarify the issue.

**Comment by tema6120** [comment]
Show me on screenshot what value is wrong and what you expect to see.

**Comment by WPFilmmaker** [comment]
Sorry! I will try to explain better:
Yesterday I autoplayed several decks (2 laps)
After the first laps finished and the new one began I returned to the main menu
the 'last tested' date was not changed, so it looked like I had not autoplayed such decks yesterday


Tonight I will try again (they were over 400 cards), I will give you more info later, if I have.

**Comment by tema6120** [comment]
In terms of my app, playing cards is not test, so 'LAST TESTED' is not overriden. It will be updated if you do exercise and at least one card is shown in the exercise.

**Comment by WPFilmmaker** [comment]
Ok got it thanks!

**Comment by WPFilmmaker** [comment]
Actually I closed it but I have a question:
I have hundreds of cards (about 800 divided into several dekcs), I don't play them all with autoplay, lets say I autoplay 400 today, tomorrow I want the other 400, how do I remember which one I already autoplayed? I have several decks and remembering them all is hard :/

**Comment by tema6120** [comment]
I think you can group the decks into separate deck lists:
![ScreenRecord-2021-04-03-16-00-12](https://user-images.githubusercontent.com/34657415/113479325-2532f080-9497-11eb-9d47-cbc824de6062.gif)

**Comment by WPFilmmaker** [comment]
Great!
