### ISSUE TITLE
You don't have any browser to open URLs

### ISSUE THREAD

**Issue by BillyHalley** [tema6120/ForgetMeNot#52]
If I click any link that should open a website it shows that message, for example in the about page if I click on the source code link, or from the add cards menu of I click on open catalog.

Not sure if it's only my phone problem, but I can't find a way to resolve this on my end

**Comment by tema6120** [comment]
What browsers do you have installed?

**Comment by BillyHalley** [comment]
I have Brave as my default, Chrome and Firefox.

I am on Android 11

**Comment by mizzunet** [comment]
Same here, I have Bromite

**Comment by tema6120** [comment]
Yes. The problem was related to Android 11. I have fixed it. Will be available in v1.8. Thank you for reporting.
