### ISSUE TITLE
Nearly unreadable content

### ISSUE THREAD

**Issue by avtkal** [tema6120/ForgetMeNot#53]
I do not know if this is happening because I have dark mode on, but I am having some problems when I press a deck's three dots and when I edit the cards.

![Screenshot_20210406-144840_ForgetMeNot](https://user-images.githubusercontent.com/63205014/113713784-024b4b00-96e8-11eb-8295-d1f81ee863c7.png)
![Screenshot_20210406-144950_ForgetMeNot](https://user-images.githubusercontent.com/63205014/113713785-02e3e180-96e8-11eb-9be8-e98710f9967a.png)

**Comment by tema6120** [comment]
I suppose you are using ForgetMeNot v1.6. Dark theme has been implemented in v1.7

**Comment by avtkal** [comment]
That was the problem, thank you!
