### ISSUE TITLE
once 'as quiz' and "mask words" mode are enabled they can't be disabled

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#6]
If one accidentally turns it on for a card or just wants to try it, it is not possible to leave such "mode" unless you go back to the main menu, disrupting the repetition flow.

Scrolling to the next card and going back to the previous card does not fix the problem. I think it would make sense to have the ability to leave such modes without having to go back to the main menu

**Comment by tema6120** [comment]
'As quiz' and 'mask letters' are not modes of exercise. These are two kind of hints. You can use them if you want to have a slight indication of an answer, for example, to know the first letter so it gives you chance to call to mind the answer. They are always available unless the card is answered or 'Walking mode' is enabled. I personally rarely use them.

**Comment by WPFilmmaker** [comment]
@tema6120 Thanks for the explanation!
