### ISSUE TITLE
Just wanted to say Thank You!

### ISSUE THREAD

**Issue by shirshak55** [tema6120/ForgetMeNot#64]
I tried Magoosh etc and all those flash card app. They were good but I wanted to create my own list. So I tried making my own app using React Native but it was too much work. And react-native was giving lots of error especially those babel related errors. 

After that, I found this and my life has certainly changed in some way. Thanks for open sourcing and I learned a lot about android architecture (Never programmed Andriod before otherthan few react native apps). 

Thanks again

**Comment by shirshak55** [comment]
Closing so I don't mess issue tracker :p

**Comment by tema6120** [comment]
Oh, it's interesting to know how the project affects others. I'm glad that you found it useful )
