### ISSUE TITLE
Make the + button to add a card permanent

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#7]
Right now when you scroll the deck sometimes the button disappears and it is quite annoying, especially because I think it is counter-intuitive. I propose to make the + button permanent while you scroll the cards.

**Comment by tema6120** [comment]
'Add card' button disappears when you scroll down, and appears when you scroll up. Such behavior of FAB (Floating Action Button) is often used in many apps, for example, in Google Drive. The logic is that when you scroll down, you are interested in the content of the page, so the FAB disappears not to obstruct content.

**Comment by tema6120** [comment]
As of v1.2 'add card' button is constantly shown. You convinced me)
