### ISSUE TITLE
Warn user if a card is already present?

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#8]
Maybe this is a bit tricky to implement but it would be nice if a user is warned if the card they are adding is already present in the deck, if you have many cards it is hard to spot a repetition.

**Comment by tema6120** [comment]
Accepted. I will report here as soon as I implement this.

**Comment by tema6120** [comment]
Implemented. As soon as the questions and answers match, the inscription "Duplicated" will appear:
![Милан](https://user-images.githubusercontent.com/34657415/106478832-4d5f9c80-64b2-11eb-9db7-747b23b008f8.png)
