### ISSUE TITLE
Ability to add bold/italic letters

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#9]
I am using ForgetMeNot for learning verbs, my cards look like the following:

top card: 
ballare
_______________
bottom card:
to dance
Io ballo
Tu balli

The first line shows the translation in English and then all the conjugations. Right now there is no way to highlight text in bold/italics or change the size. It would be a nice addition to separate text.

**Comment by tema6120** [comment]
I have no plans to support rich text. This also applies to pictures or other formats.

You can decorate the text using additional characters:
![Screenshot_1602654283](https://user-images.githubusercontent.com/34657415/95948632-999aaa00-0df9-11eb-9a10-c4303705753f.png)

**Comment by WPFilmmaker** [comment]
@tema6120 thanks! I respect your decision, but may I ask why no to images?(it was going to be a feature request :D ). The only downside from an user pov is that deck siz might grow but that's up to the user. I don't delve into difficulties in implementing it as I am not a dev :)

**Comment by tema6120** [comment]
I didn't intend to support images initially. Besides, image card is not quite fit to the way how cards are treated. My app is closely related to pronunciation of the text. Without ability to pronounce the text some functions do not work (Repetition mode, Walking mode). It can take a lot of work to adapt this feature. Taking into account the ratio of complexity and the demand for this feature, I think it is not rational to implement it at the current stage.
